language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 test_case_calc.c -o test_case_calc
  - ./test_case_calc
  - gcov test_case_calc.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
